# Global log level
level = info

# Console writer to stdout
writer = console
writer.stream = out

# Optional format
# writer.format = {date:yyyy-MM-dd HH:mm:ss} {level} [{thread}] {class}.{method}(): {message}
writer.format = {class}.{method}(): {message}
