profile_id=MyTestProfile2
p2_path=resources/profiles
target_definition=/home/ben/git-repositories/knime-sdk-setup/org.knime.sdk.setup/KNIME-AP-internal.target
install_folder=resources/installFolder
bundle_pool=resources/bundlepool
