version=2026.04.0
requiredIUs=org.eclipse.equinox.launcher,org.eclipse.equinox.p2.director,org.eclipse.equinox.p2.publisher,org.eclipse.jdt.core,org.eclipse.jface.text,org.eclipse.text
defaultRuntimeZip=
defaultRuntimeZipSha256=
